version: '3.8'

services:
  postgres:
    image: postgres:15
    platform: linux/arm64
    container_name: caretracker_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: caretracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - caretracker_network

  redis:
    image: redis:7-alpine
    platform: linux/arm64
    container_name: caretracker_redis
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - caretracker_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  caretracker_network:
    driver: bridge